---
kind: pipeline
type: docker
name: default

steps:
  - name: Typescript Linting
    image: node
    commands:
      - cd frontend
      - yarn install
      - yarn eslint . --ext .js,.jsx,.ts,.tsx

  - name: Python Linting
    image: python
    commands:
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - poetry install
      - flake8 vosekast_control
